version: '3.4'
networks:
  starter-network:
    external:
      name: starter-network

services:
  service-starter:
      image: ${REGISTRY}/ypzhuang/service-starter:${TAG}
      deploy:
        replicas: ${REPLICAS}
        restart_policy:
          condition: on-failure
      ports:
        - 8080:8080
      healthcheck:
        test: wget http://localhost:8080 --spider -q -O - > /dev/null 2>&1 || exit 1        
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 20s
      environment:
        - SPRING_PROFILES_ACTIVE=${PROFILE}
        - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
        - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
        - SPRING_REDIS_HOST=redis-service
      depends_on:
        - redis-service   
      networks:
        - starter-network

  web-console-starter:
      image: ${REGISTRY}/ypzhuang/web-console-starter:${TAG}
      deploy:
        replicas: ${REPLICAS}
        restart_policy:
          condition: on-failure
      ports:
        - 9080:80
      healthcheck:
        test: wget http://localhost:80 --spider -q -O - > /dev/null 2>&1 || exit 1        
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 20s
      environment:
        - GATEWAY_URL=http://service-starter:8080
      depends_on:
        - service-starter   
      networks:
        - starter-network

volumes:
  redis_data:
